FROM node:20-bookworm

WORKDIR /app

ENV NODE_ENV=development

COPY package.json package-lock.json ./
COPY client/package.json client/package.json
COPY server/package.json server/package.json

RUN npm ci

COPY . .

EXPOSE 3000 5173

CMD ["npm", "run", "test:env:start"]
